In [4]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score
from sklearn.preprocessing import StandardScaler

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target labels

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()  # Create a scaler object
X_train = scaler.fit_transform(X_train)  # Fit and transform the training data
X_test = scaler.transform(X_test)  # Transform the testing data

# Create a Gaussian Naive Bayes classifier
model = GaussianNB()

# Fit the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Calculate precision and recall for each class
precision = precision_score(y_test, y_pred, average=None)  # Average can be 'micro', 'macro', or None
recall = recall_score(y_test, y_pred, average=None)

# Print the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)
print("\nPrecision for each class:", precision)
print("\nRecall for each class:", recall)

# Handle an unknown state
# Example unknown data: features of an iris flower that we want to classify
unknown_flower = np.array([[5.0, 3.6, 1.4, 0.2]])  # Example unknown features

# Scale the unknown flower using the same scaler
unknown_flower_scaled = scaler.transform(unknown_flower)

# Make a prediction for the unknown flower
unknown_prediction = model.predict(unknown_flower_scaled)

# Print the prediction for the unknown flower
print("\nPredicted class for the unknown flower:", iris.target_names[unknown_prediction][0])


Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Precision for each class: [1. 1. 1.]

Recall for each class: [1. 1. 1.]

Predicted class for the unknown flower: setosa
